name: Test,Lint,Format
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.5
      - name: Install dependencies
        id: install
        run: |
          make install
      - name: Format code
        id: format
        run: |
          make format 
      - name: Lint with Ruff
        id: lint
        run: |
          make lint
      - name: Test
        id: test
        run: |
          make test